version: '3'
services:
  redis:
    image: node:18
    ports:
      - "38084:38084"
    container_name: node:18
    volumes:
      - /opt/thingwire/keti-iot-cloud/thing-wire/log:/var/log/thing-wire
    networks:
      - thingwire
    command: tail -f /dev/null

networks:
  thingwire:
    external: true

